
const vocab=window.ECOSTAT_VOCAB||[], interview=window.ECOSTAT_INTERVIEW||[];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const store={get(k,d){try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},set(k,v){localStorage.setItem(k,JSON.stringify(v))}};
let state={fav:new Set(store.get('eco_fav',[])),mastered:new Set(store.get('eco_mastered',[])),attempts:store.get('eco_attempts',0),correct:store.get('eco_correct',0),path:'ALL',page:1,perPage:24};
let deferredPrompt=null, flashDeck=[], flashIndex=0, quizCurrent=null, timerInterval=null, timerLeft=90;
function save(){store.set('eco_fav',[...state.fav]);store.set('eco_mastered',[...state.mastered]);store.set('eco_attempts',state.attempts);store.set('eco_correct',state.correct);updateStats()}
function updateStats(){const acc=state.attempts?Math.round(state.correct/state.attempts*100)+'%':'—';$('#statWords').textContent=vocab.length;$('#statMastered').textContent=state.mastered.size;$('#statFav').textContent=state.fav.size;$('#statAccuracy').textContent=acc;$('#pMastered').textContent=state.mastered.size;$('#pFav').textContent=state.fav.size;$('#pAccuracy').textContent=acc;$('#pAttempts').textContent=state.attempts?`${state.correct} correct out of ${state.attempts}`:'No attempts yet';$('#masterMeter').style.width=Math.min(100,state.mastered.size/vocab.length*100)+'%'}
function showView(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===id));scrollTo({top:0,behavior:'smooth'});if(id==='dictionary')renderDictionary();if(id==='flashcards')buildFlashDeck();if(id==='quiz')newQuiz();if(id==='progress')updateStats();}
$$('[data-view]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)));
function speak(text){if(!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='en-GB';u.rate=.88;const vs=speechSynthesis.getVoices();const uk=vs.find(v=>/en-GB/i.test(v.lang));if(uk)u.voice=uk;speechSynthesis.speak(u)}
const cats=[...new Set(vocab.map(x=>x.category))].sort();for(const sel of [$('#catFilter'),$('#flashCat')])cats.forEach(c=>{const o=document.createElement('option');o.value=c;o.textContent=c;sel.append(o)});
function matchesPath(e,path){if(path==='ALL')return true;if(path==='FAV')return state.fav.has(e.id);if(path==='COMMON')return e.pathways.includes('COMMON');return e.pathways.includes(path)||e.pathways.includes('COMMON')}
function filtered(){const q=$('#search').value.trim().toLowerCase(), cat=$('#catFilter').value, src=$('#sourceFilter').value;return vocab.filter(e=>matchesPath(e,state.path)&&(!cat||e.category===cat)&&(!src||e.source===src)&&(!q||[e.term,e.fr,e.definition,e.category,e.source,...e.pathways].join(' ').toLowerCase().includes(q)))}
function renderDictionary(){const list=filtered(), pages=Math.max(1,Math.ceil(list.length/state.perPage));state.page=Math.min(state.page,pages);$('#resultsMeta').textContent=`${list.length} entr${list.length===1?'y':'ies'} · page ${state.page}/${pages}`;const slice=list.slice((state.page-1)*state.perPage,state.page*state.perPage);$('#wordGrid').innerHTML=slice.map(e=>`<article class="word-card"><div class="visual" aria-hidden="true">${e.visual}</div><div><h3>${e.term}</h3><div class="ipa">${e.ipa}</div><div class="translation">${e.fr}</div><p class="definition">${e.definition}</p><div class="badges"><span class="badge">${e.category}</span>${e.pathways.map(p=>`<span class="badge path">${p}</span>`).join('')}</div></div><div class="card-actions"><button class="smallbtn" data-speak="${e.id}" aria-label="Listen to ${e.term}">🔊</button><button class="smallbtn ${state.fav.has(e.id)?'on':''}" data-fav="${e.id}" aria-label="Favourite">★</button><button class="smallbtn" data-open="${e.id}" aria-label="Open details">↗</button></div></article>`).join('');$('#pager').innerHTML=[...Array(pages)].slice(Math.max(0,state.page-4),Math.min(pages,state.page+3)).map((_,i)=>{const n=Math.max(1,state.page-3)+i;return n<=pages?`<button data-page="${n}" ${n===state.page?'disabled':''}>${n}</button>`:''}).join('');bindCards()}
function bindCards(){$$('[data-speak]').forEach(b=>b.onclick=()=>speak(vocab.find(x=>x.id==b.dataset.speak).term));$$('[data-fav]').forEach(b=>b.onclick=()=>{const id=+b.dataset.fav;state.fav.has(id)?state.fav.delete(id):state.fav.add(id);save();renderDictionary()});$$('[data-open]').forEach(b=>b.onclick=()=>openWord(+b.dataset.open));$$('[data-page]').forEach(b=>b.onclick=()=>{state.page=+b.dataset.page;renderDictionary()})}
function openWord(id){const e=vocab.find(x=>x.id===id);$('#wordModalBody').innerHTML=`<div style="font-size:4rem">${e.visual}</div><div class="eyebrow">${e.category}</div><h2 style="font-size:2.2rem;margin:.2em 0">${e.term}</h2><div class="ipa">${e.ipa}</div><h3>${e.fr}</h3><p>${e.definition}</p><div class="badges">${e.pathways.map(p=>`<span class="badge path">${p}</span>`).join('')}<span class="badge">${e.source}</span></div><div class="hero-actions"><button class="ghost" onclick="speak(${JSON.stringify(e.term)})">🔊 British English audio</button><button class="primary" onclick="toggleMaster(${e.id})">${state.mastered.has(e.id)?'✓ Mastered':'Mark as mastered'}</button></div>`;openModal('wordModal')}
window.toggleMaster=id=>{state.mastered.has(id)?state.mastered.delete(id):state.mastered.add(id);save();openWord(id)};window.speak=speak;
$('#search').oninput=()=>{state.page=1;renderDictionary()};$('#catFilter').onchange=$('#sourceFilter').onchange=()=>{state.page=1;renderDictionary()};$$('#pathChips .chip').forEach(b=>b.onclick=()=>{$$('#pathChips .chip').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.path=b.dataset.path;state.page=1;renderDictionary()});
$$('[data-home-path]').forEach(b=>b.onclick=()=>{const path=b.dataset.homePath;state.path=path;state.page=1;$$('#pathChips .chip').forEach(x=>x.classList.toggle('active',x.dataset.path===path));showView('dictionary')});
function buildFlashDeck(){const p=$('#flashPath').value,cat=$('#flashCat').value,fav=$('#flashFav').checked;flashDeck=vocab.filter(e=>matchesPath(e,p)&&(!cat||e.category===cat)&&(!fav||state.fav.has(e.id))).sort(()=>Math.random()-.5);flashIndex=0;renderFlash()}
function renderFlash(){if(!flashDeck.length){$('#flashCard').innerHTML='<p>No cards match these filters.</p>';$('#flashCount').textContent='';return}const e=flashDeck[flashIndex%flashDeck.length];$('#flashCard').classList.remove('flipped');$('#flashCard').innerHTML=`<div class="front"><div class="big-visual">${e.visual}</div><div class="eyebrow">${e.category}</div><h2>${e.term}</h2><div class="ipa">${e.ipa}</div><p class="hint">Tap to reveal</p></div><div class="back"><div class="big-visual">${e.visual}</div><h2>${e.fr}</h2><p style="font-size:1.15rem">${e.definition}</p><div class="badges" style="justify-content:center">${e.pathways.map(p=>`<span class="badge path">${p}</span>`).join('')}</div></div>`;$('#flashCount').textContent=`Card ${flashIndex+1} of ${flashDeck.length}`}
$('#flashCard').onclick=()=>$('#flashCard').classList.toggle('flipped');$('#flashCard').onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();$('#flashCard').click()}};$('#againBtn').onclick=()=>{flashIndex=(flashIndex+1)%Math.max(1,flashDeck.length);renderFlash()};$('#masterBtn').onclick=()=>{if(!flashDeck.length)return;state.mastered.add(flashDeck[flashIndex].id);save();flashIndex=(flashIndex+1)%flashDeck.length;renderFlash()};$('#speakFlash').onclick=()=>flashDeck.length&&speak(flashDeck[flashIndex].term);$('#shuffleFlash').onclick=buildFlashDeck;$('#flashPath').onchange=$('#flashCat').onchange=$('#flashFav').onchange=buildFlashDeck;
function qPool(){const p=$('#quizPath').value;return vocab.filter(e=>matchesPath(e,p))}
function sample(arr,n){return [...arr].sort(()=>Math.random()-.5).slice(0,n)}
function newQuiz(){const pool=qPool();if(pool.length<4)return;quizCurrent=pool[Math.floor(Math.random()*pool.length)];const mode=$('#quizMode').value;let html=`<div class="question-visual">${quizCurrent.visual}</div><div class="eyebrow">${quizCurrent.category}</div>`;if(mode==='mcq'){html+=`<h2>${quizCurrent.definition}</h2><p class="mini-note">Which word matches this definition?</p>`;let opts=sample(pool.filter(x=>x.id!==quizCurrent.id),3).concat(quizCurrent).sort(()=>Math.random()-.5);html+=`<div class="answers">${opts.map(o=>`<button class="answer" data-qid="${o.id}">${o.term}</button>`).join('')}</div>`}else if(mode==='fr'){html+=`<h2>${quizCurrent.term}</h2><div class="ipa">${quizCurrent.ipa}</div><p class="mini-note">Choose the best French translation.</p>`;let opts=sample(pool.filter(x=>x.id!==quizCurrent.id),3).concat(quizCurrent).sort(()=>Math.random()-.5);html+=`<div class="answers">${opts.map(o=>`<button class="answer" data-qid="${o.id}">${o.fr}</button>`).join('')}</div>`}else{html+=`<h2>${quizCurrent.definition}</h2><p class="mini-note">Type the English term.</p><div class="type-input"><input id="typeAnswer" autocomplete="off"><button id="checkType" class="primary">Check</button></div><div id="typeFeedback" class="mini-note" style="margin-top:12px"></div>`}$('#quizCard').innerHTML=html;$$('[data-qid]').forEach(b=>b.onclick=()=>checkChoice(b,+b.dataset.qid));if($('#checkType')){$('#checkType').onclick=checkType;$('#typeAnswer').onkeydown=e=>e.key==='Enter'&&checkType()}updateQuizScore()}
function checkChoice(btn,id){if($$('.answer.correct,.answer.wrong').length)return;state.attempts++;const ok=id===quizCurrent.id;if(ok){state.correct++;btn.classList.add('correct')}else{btn.classList.add('wrong');const c=$(`[data-qid="${quizCurrent.id}"]`);if(c)c.classList.add('correct')}save();updateQuizScore();setTimeout(newQuiz,900)}
function normaliseAnswer(s){return s.toLowerCase().replace(/^(an?|the|to)\s+/,'').replace(/[^a-z0-9]+/g,'')}
function checkType(){const v=$('#typeAnswer').value;state.attempts++;const ok=normaliseAnswer(v)===normaliseAnswer(quizCurrent.term);if(ok)state.correct++;save();$('#typeFeedback').innerHTML=ok?`✅ Correct — <strong>${quizCurrent.term}</strong>`:`❌ Expected: <strong>${quizCurrent.term}</strong>`;setTimeout(newQuiz,1200)}
function updateQuizScore(){const a=state.attempts?Math.round(state.correct/state.attempts*100):0;$('#quizScore').textContent=`Session record: ${state.correct}/${state.attempts} correct${state.attempts?` · ${a}%`:''}`}
$('#newQuiz').onclick=newQuiz;$('#quizMode').onchange=$('#quizPath').onchange=newQuiz;
function newInterview(){const q=interview[Math.floor(Math.random()*interview.length)];$('#interviewQ').textContent=q.q;$('#interviewTag').textContent=q.tag;resetTimer()}function resetTimer(){clearInterval(timerInterval);timerInterval=null;timerLeft=90;$('#timer').textContent='01:30';$('#timerBtn').textContent='Start 90-sec timer'}function fmt(sec){return `${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`}$('#timerBtn').onclick=()=>{if(timerInterval){resetTimer();return}$('#timerBtn').textContent='Reset timer';timerInterval=setInterval(()=>{timerLeft--;$('#timer').textContent=fmt(Math.max(0,timerLeft));if(timerLeft<=0){clearInterval(timerInterval);timerInterval=null;$('#timerBtn').textContent='Time! — reset'}},1000)};$('#newInterview').onclick=newInterview;
function openModal(id){$('#'+id).classList.add('open')}function closeModal(id){$('#'+id).classList.remove('open')}$$('[data-close]').forEach(b=>b.onclick=()=>closeModal(b.dataset.close));$$('.modal').forEach(m=>m.onclick=e=>{if(e.target===m)m.classList.remove('open')});$('#a11yBtn').onclick=()=>openModal('a11yModal');
const A=store.get('eco_a11y',{});for(const [id,cls] of [['largeText','large-text'],['highContrast','high-contrast'],['readable','readable'],['reduceMotion','reduce-motion']]){const el=$('#'+id);el.checked=!!A[id];document.body.classList.toggle(cls,el.checked);el.onchange=()=>{document.body.classList.toggle(cls,el.checked);A[id]=el.checked;store.set('eco_a11y',A)}}
function appInstalled(){return window.matchMedia('(display-mode: standalone)').matches||window.navigator.standalone===true}
function refreshInstallUI(){const btn=$('#installHero'),hint=$('#installHint');if(!btn||!hint)return;if(appInstalled()){btn.textContent='Installed';btn.disabled=true;hint.textContent='App installed on this device.'}else if(deferredPrompt){btn.textContent='Install app';btn.disabled=false;hint.textContent='Ready to install on this device.'}else{btn.textContent='Install app';btn.disabled=false;hint.textContent='Install it once. Revise anywhere.'}}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;refreshInstallUI()});window.addEventListener('appinstalled',()=>{deferredPrompt=null;refreshInstallUI()});async function installApp(){if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;refreshInstallUI()}else openModal('installModal')}$('#installHero').onclick=installApp;
function renderSpotlight(){const host=$('#homeSpotlight');if(!host||!vocab.length)return;const course=vocab.filter(e=>e.source==='Course 2026');const pool=course.length?course:vocab;const now=new Date();const dayKey=Math.floor(new Date(now.getFullYear(),now.getMonth(),now.getDate()).getTime()/86400000);const e=pool[Math.abs(dayKey)%pool.length];host.innerHTML=`<div class="spotlight-label">Word spotlight · ${e.category}</div><div class="spotlight-row"><div><div class="spotlight-term">${e.term}</div><div class="spotlight-ipa">${e.ipa}</div><div class="spotlight-fr">${e.fr}</div><p class="spotlight-definition">${e.definition}</p></div><div class="spotlight-actions"><button class="smallbtn" id="spotSpeak" aria-label="Listen to ${e.term}">🔊</button><button class="smallbtn" id="spotOpen" aria-label="Open ${e.term}">↗</button></div></div>`;$('#spotSpeak').onclick=()=>speak(e.term);$('#spotOpen').onclick=()=>openWord(e.id)}
$('#exportBtn').onclick=()=>{const data={version:1,favourites:[...state.fav],mastered:[...state.mastered],attempts:state.attempts,correct:state.correct,exportedAt:new Date().toISOString()};const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='ecostat-english-progress.json';a.click();URL.revokeObjectURL(a.href)};$('#importFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const d=JSON.parse(await f.text());state.fav=new Set(d.favourites||[]);state.mastered=new Set(d.mastered||[]);state.attempts=+d.attempts||0;state.correct=+d.correct||0;save();alert('Progress imported.')}catch{alert('This file could not be imported.')}};$('#resetBtn').onclick=()=>{if(confirm('Reset all favourites, mastery and quiz statistics?')){state.fav.clear();state.mastered.clear();state.attempts=state.correct=0;save()}};
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
updateStats();renderSpotlight();refreshInstallUI();renderDictionary();buildFlashDeck();newQuiz();newInterview();
